name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # INstall Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'
    
    # Install the newman command line utility and also install the html extra reporter
    - name: Install newman
      run: |
       npm install -g newman
       # npm install -g newman-reporter-htmlextra

    # Make directory to upload the test results
#    - name: Make Directory for results
 #     run: mkdir -p testResults


    # Run the POSTMAN collection
    - name: Run POSTMAN collection
      run: |
       newman run https://api.getpostman.com/collections/15503808-5fc512ec-2d17-407b-acc5-b8d4ec08fe63?apikey=PMAK-624a0fd2b5b87347fc0e3120-99711121ee85715f0db2ac780d865c9e9f 
       --environment https://api.getpostman.com/environments/15503808-80269675-a497-4902-84b1-270fc74a65c0?apikey=PMAK-624a0fd2b5b87347fc0e3120-99711121ee85715f0db2ac780d865c9e9f
       
       #newman run https://www.getpostman.com/collections/691bf332d21f238d3c54 -e https://www.postman.com/gold-robot-529468/workspace/test-postman/environment/15503808-80269675-a497-4902-84b1-270fc74a65c0
       #-x -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

    # Upload the contents of Test Results directory to workspace
   # - name: Output the run Details
    #  uses: actions/upload-artifact@v2
     # with: 
      # name: RunReports
       #path: testResults
